name: attendx
description: "AttendX - Secure Attendance. Smarter Campus."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  qr_flutter: ^4.1.0
  fl_chart: ^0.68.0
  intl: ^0.19.0
  provider: ^6.1.2
  http: ^1.6.0
  dotenv: ^4.2.0
  flutter_dotenv: ^6.0.1
  flutter_secure_storage: ^11.2.0
  local_auth: ^3.0.2
  connectivity_plus: ^7.3.1
  mobile_scanner: ^7.4.2
  uuid: ^4.6.0
  path_provider: ^2.1.6
  share_plus: ^13.3.0
  flutter_liveness_detection: ^1.0.3
  permission_handler: ^12.0.3
  camera: ^0.11.4
  flutter_liveness_check: ^1.0.1
  google_mlkit_face_detection: ^0.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
  - .env
  - assets/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app-logo.jpeg"
  min_sdk_android: 21
